/* Auto-generated by tools/png_to_tiles.py from assets/sprites/dialog_arrow.png -- do not edit manually */
#pragma bank 255
#include <stdint.h>
#include "banking.h"

BANKREF(dialog_arrow_tile_data)
const uint8_t dialog_arrow_tile_data[] = {
    /* tile 0 */ 0x00, 0x00, 0xFF, 0x00, 0x81, 0x7E, 0x81, 0x7E, 0x42, 0x3C, 0x24, 0x18, 0x18, 0x00, 0x00, 0x00,
};

const uint8_t dialog_arrow_tile_data_count = 1u;
