/* Auto-generated by tools/png_to_tiles.py from assets/sprites/player_car.png -- do not edit manually */
#pragma bank 255
#include <stdint.h>
#include "banking.h"

/* Bank reference: volatile __at(bank) places the bank symbol in DATA (not CODE),
   so bankpack assigns it to the same bank as this file's data array.
   BANKREF() creates a CODE stub that bankpack may assign to a different bank. */
volatile __at(255) uint8_t __bank_player_tile_data;

const uint8_t player_tile_data[] = {
    /* tile 0 */ 0x3C, 0x3C, 0x7E, 0x7E, 0xFF, 0xFF, 0xFF, 0xC3, 0xFF, 0xC3, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    /* tile 1 */ 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7E, 0x7E, 0x7E, 0x7E, 0x7E, 0x7E, 0x3C, 0x3C,
};

const uint8_t player_tile_data_count = 2u;
