/* Auto-generated by tools/png_to_tiles.py from assets/sprites/player_car.png -- do not edit manually */
#pragma bank 255
#include <stdint.h>
#include "banking.h"

/* Bank reference: BANKREF(name) emits a CODE stub; bankpack rewrites
   ___bank_name to the actual assigned bank at link time.
   Required for autobank (255) so BANK(name) returns the real bank. */
BANKREF(player_tile_data)

const uint8_t player_tile_data[] = {
    /* tile 0 */ 0x3C, 0x3C, 0x7E, 0x7E, 0xFF, 0xFF, 0xFF, 0xC3, 0xFF, 0xC3, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    /* tile 1 */ 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7E, 0x7E, 0x7E, 0x7E, 0x7E, 0x7E, 0x3C, 0x3C,
};

const uint8_t player_tile_data_count = 2u;
